backend:
  name: git-gateway
  branch: main # or your default branch

media_folder: "static/uploads" # Folder where uploaded media will go
public_folder: "/uploads" # Public URL path to access the media

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
